[
tool.poetry
]
name = "logic-gates"
version = "0.1.0"
description = "A Python implementation of digital logic gates"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
packages = [{include = "logic_gates", from = "src"}]

[
tool.poetry.dependencies
]
python = "^3.8"

[
tool.poetry.group.dev.dependencies
]
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
black = "^23.7.0"
isort = "^5.12.0"
flake8 = "^6.1.0"

[
build-system
]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[
tool.pytest.ini_options
]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "--cov=logic_gates --cov-report=term-missing"

[
tool.black
]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'

[
tool.isort
]
profile = "black"
multi_line_output = 3
